project:
  type: book
  output-dir: ../docs 

book:
  title: "Writing Reproducible Manuscripts in R & Python"
  author: "Research Data Management Support<br>Utrecht University"
  date: last-modified
  chapters:
    - index.qmd
    - acknowledgements.qmd
    - schedule.qmd
    - part: Preparation
      chapters:
        - installation-and-setup.qmd
        - workshop-materials.qmd
    - introduction.qmd
    - getting-started.qmd
    - part: Writing
      chapters:
        - markdown-syntax.qmd
        - referencing.qmd
    - part: Code
      chapters:
        - code-chunks.qmd 
        - inline-code.qmd
        - sourcing-code.qmd
    - rendering.qmd
    - part: Bonus
      chapters:
        - dependency-management.qmd
        - version-control.qmd
        - archiving-and-publishing.qmd
    - references.qmd
  repo-url: https://github.com/UtrechtUniversity/workshop-reproducible-manuscripts
  repo-actions: [edit]

bibliography: references.bib

format:
  html:
    theme: cosmo

callout-appearance: simple