# Writing {.unnumbered}

# Writing

The body of the document is where you will do your writing, which will primarily be in the [Markdown](https://daringfireball.net/projects/markdown/syntax) format (LaTeX and HTML would also work, depending on the output format).

## Markdown Syntax

If you're not familiar with Markdown, you can familiarize yourself with it in a couple of minutes using the following link: [https://learnxinyminutes.com/docs/markdown/](https://learnxinyminutes.com/docs/markdown/).

Additionally, you can use the [Visual Editor](https://rstudio.github.io/visual-markdown-editing/) option in RStudio to see Markdown syntax previewed in it's final format as you write. 

Some things you can do with Markdown:

- Headings can be created for sections and subsections using the `#` hashtag character. So `# Heading 1` for a top-level heading and `## Heading 2` for a second-level heading and so on. 

- Text can be formatted in *italic* or **bold** using the `*` asterisk character.

- Bullet point lists can be created with a `-` hyphen or `*` asterisk for each line in the list.

- Links can be embedded by writing in the following way: [insert text which should be hyperlinked](insert link to website)

- Plain code can be embedded in text using the ``` backtick character. R code can be embedded as well, but we will cover that in the next section.

## Exercise